// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SCPSLApiNodeJS;
//
//    var steamId = SteamId.FromJson(jsonString);

namespace AtlasUserAPI.JSON
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Login
    {
        [JsonProperty("steamid64", NullValueHandling = NullValueHandling.Ignore)]
        public string Steamid64 { get; set; }

        [JsonProperty("ip", NullValueHandling = NullValueHandling.Ignore)]
        public string Ip { get; set; }
    }

    public partial class Login
    {
        public static Login FromJson(string json) => JsonConvert.DeserializeObject<Login>(json, AtlasUserAPI.JSON.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Login self) => JsonConvert.SerializeObject(self, AtlasUserAPI.JSON.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
