// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SCPSLApiNodeJS.JSON;
//
//    var succesResponseSteamId = SuccesResponseSteamId.FromJson(jsonString);

namespace SanctionSystem.JSON.Success
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SuccessResponseJSON
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class SuccessResponseJSON
    {
        public static SuccessResponseJSON FromJson(string json) => JsonConvert.DeserializeObject<SuccessResponseJSON>(json, SanctionSystem.JSON.Success.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SuccessResponseJSON self) => JsonConvert.SerializeObject(self, SanctionSystem.JSON.Success.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
