// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SCPSLApiNodeJS.JSON.Error;
//
//    var errorResponseSteamId = ErrorResponseSteamId.FromJson(jsonString);

namespace SanctionSystem.JSON.Error
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ErrorResponseJSON
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class ErrorResponseJSON
    {
        public static ErrorResponseJSON FromJson(string json) => JsonConvert.DeserializeObject<ErrorResponseJSON>(json, SanctionSystem.JSON.Error.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ErrorResponseJSON self) => JsonConvert.SerializeObject(self, SanctionSystem.JSON.Error.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
